source 'https://rubygems.org'

ruby ">= 3.2.0"

gem 'cocoapods', '>= 1.15.2'
gem 'activesupport', '>= 7.0', '< 8'
gem 'xcodeproj', '>= 1.26.0'
gem 'concurrent-ruby', '>= 1.3.4'

# Ruby 3.4+ removed some default gems.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
